### PR TITLE
Create webpage with user info

### PR DESCRIPTION
**Pull request by collinsnji**
Created a jekyll page to show all the info for all users. Also, added service-worker to cache images to increase load time. Page link: https://collinsnji.github.io/github-users-africa/users.html

### CODE REVIEW

**Comment by collinsnji** [comment]
@Ch3ck please review :)

**Comment by ch3ck** [comment]
@collinsnji user data is not sorted. Also add user instructions for sorting data with sort.js to README.md

**Review by ch3ck — CHANGES_REQUESTED** [review]
Make the changes, I commented above then we should be good to go

**Review by ch3ck — APPROVED** [review]
This should be good to go

**Pull request merged**
